@LocationCheck.API_HostAddress = http://localhost:5100

GET {{LocationCheck.API_HostAddress}}/location/
Accept: application/json

###

GET {{LocationCheck.API_HostAddress}}/location1/
Accept: applicati
