@LocationCheck.API_HostAddress = http://localhost:5100

GET {{LocationCheck.API_HostAddress}}/location/check
Accept: application/json

###

GET {{LocationCheck.API_HostAddress}}/location/users
Accept: application/json

###